project/ecg/urls.py
from django.urls import path
from . import views
from .views import (Questions_view, dis_information_view, RecordView, UserDetailView)

app_name = "ecg"
urlpatterns = [
    path('login/', views.Login, name="login"), # 로그인 URL
    path('logout/', views.Logout, name="logout"), # 로그아웃
    path('signup/', views.Signup, name="signup"), # 회원가입 URL
    path('get_chart_data/', views.get_chart_data, name='get_chart_data'),
    path('chart/', views.chart_view, name='chart_view'),
    path('record/', RecordView.as_view(), name='record'),
    path('dis_information/', dis_information_view, name='dis_information'),
    path('inform/', UserDetailView.as_view(), name='inform'),
    path('questions/', Questions_view, name='questions'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ecg/', include('ecg.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/templates/page.html
<html lang="ko-kr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <title>심장 질환 검사</title>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://code.highcharts.com/highcharts.js"></script>
</head>

<body>
{% load static %}
<link rel="stylesheet" href="{% static 'page.css' %}">

{% block title %}

{% endblock title %}
<div id="title-container">
    <p id="current-date" style="text-align: right;">{% now "Y년 m월 d일  H시i분 " %}</p>
</div>
    <div id="grid">
        <nav class="nav flex-column">
            <a href="{% url 'ecg:chart_view'%}" class="nav-link">심전도 검사</a>
            <a href="{% url 'ecg:record'%}" class="nav-link">건강 기록</a>
            <a href="{% url 'ecg:dis_information'%}" class="nav-link">질병 및 질환 정보</a>
            <a href="{% url 'ecg:inform'%}" class="nav-link">회원 정보</a>
            <a href="{% url 'ecg:logout'%}" class="nav-link">로그 아웃</a>
        </nav>
        <div>
        {% block content %}

        {% endblock content %}
        </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>