project/ecg/urls.py
from django.urls import path
from . import views
from .views import (Questions_view, dis_information_view, RecordView, UserDetailView)

app_name = "ecg"
urlpatterns = [
    path('login/', views.Login, name="login"), # 로그인 URL
    path('logout/', views.Logout, name="logout"), # 로그아웃
    path('signup/', views.Signup, name="signup"), # 회원가입 URL
    path('get_chart_data/', views.get_chart_data, name='get_chart_data'),
    path('chart/', views.chart_view, name='chart_view'),
    path('record/', RecordView.as_view(), name='record'),
    path('dis_information/', dis_information_view, name='dis_information'),
    path('inform/', UserDetailView.as_view(), name='inform'),
    path('questions/', Questions_view, name='questions'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ecg/', include('ecg.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/ecg/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import date

class Duser(AbstractUser):
    sex = models.CharField(max_length=20, null=True)
    b_type = models.CharField(max_length=30, null=True)
    height = models.IntegerField(blank=True, null=True)
    weight = models.IntegerField(blank=True, null=True)
    birth = models.DateField(blank=True, null=True)

class Questions(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)
    question1 = models.BooleanField(default=False, verbose_name='턱, 목 또는 등쪽에 통증이나 불편함이 있다.')
    question2 = models.BooleanField(default=False, verbose_name='가족중 고혈압이나 심장병이 있다.')
    question3 = models.BooleanField(default=False, verbose_name='가슴에 통증이나 불편감이 있다.')
    question4 = models.BooleanField(default=False, verbose_name='숨이 찬다.')
    question5 = models.BooleanField(default=False, verbose_name='힘이 없고, 어지럽다.')
    question6 = models.BooleanField(default=False, verbose_name='한쪽 또는 양쪽 눈이 흐리게 보인다.')
    question7 = models.BooleanField(default=False, verbose_name='팔 또는 어깨에 통증이나 불편감이 있다.')
    total = models.IntegerField(default=0, editable=False)
    status = models.CharField(max_length=20, default='')
    u_id = models.ForeignKey(Duser, on_delete=models.CASCADE)

class ChartData(models.Model):
    value = models.IntegerField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.value} at {self.timestamp}"
    
class Avg(models.Model):
    avg = models.FloatField(default=0)
    status = models.CharField(max_length=20, default='')
    timestamp = models.DateTimeField(auto_now_add=True)
    u_id = models.ForeignKey(Duser, on_delete=models.CASCADE)

project/ecg/forms.py
from django import forms
from ecg.models import Duser, Questions
from django.contrib.auth.forms import UserCreationForm
from django.forms import DateInput
from django.core.exceptions import ValidationError
#회원가입
class SignupForm(UserCreationForm):
    SEX = {
        ('남','남'),
        ('여','여'),
    }
    STATUS = {
        ('Rh-A','Rh-A'),
        ('Rh+A','Rh+A'),
        ('Rh-B','Rh-B'),
        ('Rh+B','Rh-B'),
        ('Rh-O','Rh-O'),
        ('Rh+O','Rh+O'),
        ('Rh-AB','Rh-AB'),
        ('Rh+AB','Rh+AB'),
    }
    sex = forms.ChoiceField(label='성별', choices=SEX, required=True)
    b_type = forms.ChoiceField(label='혈액', choices=STATUS, required=True)
    birth = forms.DateField(label='생년월일', widget=forms.DateInput(attrs={'type': 'date'}))
    height = forms.CharField(label='키(cm)')
    weight = forms.CharField(label='몸무게(kg)')
    class Meta:
        model= Duser
        fields = ('first_name', 'last_name', 'birth', 'username', 'password1', 'password2', 'email', 'sex', 'b_type', 'height', 'weight')

# class QuestionsForm(forms.ModelForm):
#     class Meta:
#         model = Questions
#         fields = ['question1', 'question2', 'question3', 'question4', 'question5', 'question6', 'question7']
# class CustomRadioSelect(forms.RadioSelect):
#     def render(self, name, value, attrs=None, choices=()):
#         # Only render the radio buttons for 'yes' and 'no' choices
#         final_choices = [(k, v) for k, v in choices if k in ['yes', 'no']]
#         return super().render(name, value, attrs, final_choices)

#class QuestionsForm(forms.ModelForm):
#    class Meta:
#        model = Questions
#        fields = '__all__'
#        widgets = {
#            'question1': forms.RadioSelect(choices=[(True, 'Yes'), (False, 'No')]),
#            'question2': forms.RadioSelect(choices=[(True, 'Yes'), (False, 'No')]),
#            'question3': forms.RadioSelect(choices=[(True, 'Yes'), (False, 'No')]),
#            'question4': forms.RadioSelect(choices=[(True, 'Yes'), (False, 'No')]),
#            'question5': forms.RadioSelect(choices=[(True, 'Yes'), (False, 'No')]),
#            'question6': forms.RadioSelect(choices=[(True, 'Yes'), (False, 'No')]),
#            'question7': forms.RadioSelect(choices=[(True, 'Yes'), (False, 'No')]),
#        }

class QuestionsForm(forms.ModelForm):
    class Meta:
        model = Questions
        fields = ['question1', 'question2', 'question3', 'question4', 'question5', 'question6', 'question7']
        widgets = {
            'question1': forms.RadioSelect(choices=((True, 'Yes'), (False, 'No'))),
            'question2': forms.RadioSelect(choices=((True, 'Yes'), (False, 'No'))),
            'question3': forms.RadioSelect(choices=((True, 'Yes'), (False, 'No'))),
            'question4': forms.RadioSelect(choices=((True, 'Yes'), (False, 'No'))),
            'question5': forms.RadioSelect(choices=((True, 'Yes'), (False, 'No'))),
            'question6': forms.RadioSelect(choices=((True, 'Yes'), (False, 'No'))),
            'question7': forms.RadioSelect(choices=((True, 'Yes'), (False, 'No'))),
        }

project/ecg/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.contrib.auth.decorators import login_required
from .forms import SignupForm, QuestionsForm
from .models import Duser, Questions, ChartData, Avg
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.views.generic import DetailView, ListView
from datetime import datetime
from pytz import timezone
from django.views.decorators.csrf import csrf_exempt
#회원가입
def Signup(request):
    if request.method == "GET":
        signupForm = SignupForm()
        context = {'signupForm': signupForm}
        return render(request, 'ecg/signup.html', context)
    
    elif request.method == "POST":
        signupForm = SignupForm(request.POST)
        if signupForm.is_valid():
            duser = signupForm.save(commit=False)
            duser.save()
            # Redirect to the login page upon successful registration
            return redirect("ecg:login")
        else:
            # If registration fails, return the form with errors
            return render(request, 'ecg/signup.html', {'signupForm': signupForm})
#로그인
def Login(request):
    if request.method == "POST":
        loginForm = AuthenticationForm(request, request.POST)
        if loginForm.is_valid():
            print("인증성공")
            auth_login(request, loginForm.get_user())
            return redirect("ecg:chart_view")
        else:
            print("인증실패")
            return render(request, 'ecg/login.html', {'error': '로그인 실패'})
    return render(request, 'ecg/login.html')

#로그아웃
def Logout(request):
    user = request.user.username
    auth_logout(request)
    return redirect("ecg:login")

#회원정보
class UserDetailView(LoginRequiredMixin, DetailView):
    model = Duser
    template_name = 'ecg/inform_detail.html'
    context_object_name = 'user'
    
    def get_object(self, queryset=None):
        return self.request.user

# 동적 차트

@login_required
def get_chart_data(request):
    start_time_str = request.GET.get('start_time')
    if not start_time_str:
        return JsonResponse({'data': []})

    try:
        start_time = datetime.strptime(start_time_str, '%Y-%m-%dT%H:%M:%S.%fZ')
        start_time = start_time.replace(tzinfo=timezone('UTC'))
    except ValueError:
        return JsonResponse({'data': [], 'error': 'Invalid timestamp format'})

    data = ChartData.objects.filter(timestamp__gte=start_time).order_by('timestamp')
    data_values = [item.value for item in data]
    return JsonResponse({'data': data_values})

@login_required
def chart_view(request):
    if request.method == 'POST':
        avg_value = float(request.POST.get('avg_value'))
        status = request.POST.get('status')
        new_avg = Avg(avg=avg_value, status=status, u_id=request.user)
        new_avg.save()
        return JsonResponse({'status': 'success'})
    return render(request, 'ecg/chart.html')

#건강체크
@login_required
def Questions_view(request):
    if request.method == 'POST':
        form = QuestionsForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)

            # Calculate the total based on the selected 'yes' answers
            total = sum([int(getattr(instance, f)) for f in form.Meta.fields if getattr(instance, f)])
            instance.total = total
            instance.u_id = request.user

            # Conditional statements based on the total value
            if total == 0:
                instance.status = '양호'
                result_message = "지금 현재 양호한 상태입니다。"
            elif total >= 3 and total <=5 :
                instance.status = '주의'
                result_message = "건강 상태가 좋지 않습니다。 가까운 병원에 방문하시길 바랍니다。"
            elif total > 5:
                instance.status = '심각'
                result_message = "지금 즉시 응급실로 연락하시길 바랍니다。"
            else:
                instance.status = '양호'
                result_message = "지금 현재 양호한 상태입니다。"

            instance.save()

            return render(request, 'ecg/questions.html', {'form': form, 'questions': Questions.objects.filter(u_id=request.user), 'result_message': result_message})

    else:
        form = QuestionsForm()
        result_message = ""

    questions = Questions.objects.filter(u_id=request.user)
    return render(request, 'ecg/questions.html', {'form': form, 'questions': questions, 'result_message': result_message})

# 건강기록
class RecordView(LoginRequiredMixin, ListView):
    model = Avg
    template_name = 'ecg/record.html'
    context_object_name = 'record'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['all_avgs'] = Avg.objects.filter(u_id=self.request.user).order_by('timestamp')
        context['all_questions'] = Questions.objects.filter(u_id=self.request.user).order_by('id')
        return context
    
# 질병 및 질환 정보
def dis_information_view(request):
    return render(request, 'ecg/dis_information.html')

project/ecg/templates/ecg/chart.html
{% extends 'page.html' %}
<html lang="ko-kr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    {% block title %}
    <h1 id="title">심장 질환 모니터링</h1>
    {% endblock title %}
    {% block content %}
    <div id="chart-container" style="width:100%; height:100%;"></div>
    <button class="btn btn-primary" id="loadDataButton">측정</button>
    <div id="currentValue"></div>
    <div id="average"></div>
    <script>
    var chart;
    var total = 0;
    var count = 0;
    var stopPolling = false;
    var lastValue = null;

    document.getElementById('loadDataButton').addEventListener('click', function () {
        var startTime = new Date().toISOString();
        chart = Highcharts.chart('chart-container', {
            xAxis: { max: 60 },
            series: [{ type: 'spline' }],
            plotOptions: { series: { animation: false } }
        });
    
        stopPolling = false;
        fetchDataLoop(startTime); // 시작

        setTimeout(function () {
            stopPolling = true;
            var average = total / count;
            var healthStatus = '';
            if (average < 60) healthStatus = '서맥';
            else if (average < 100) healthStatus = '정상';
            else healthStatus = '빈맥';
    
            var userResponse = confirm('심박수 상태 - ' + healthStatus + '. 확인 버튼을 누르면 건강 체크 페이지로 이동합니다.');
            if (userResponse) {
                $.ajax({
                    url: '{% url "ecg:chart_view" %}',
                    type: 'POST',
                    data: {
                        'avg_value': average,
                        'status': healthStatus,
                        'csrfmiddlewaretoken': '{{ csrf_token }}'
                    },
                    success: function (response) {
                        if (response.status === 'success') {
                            window.location.href = "{% url 'ecg:questions' %}";
                        }
                    }
                });
            }
        }, 60000);
    });

function fetchDataLoop(startTime) {
    if (stopPolling) return;

    $.ajax({
        url: '{% url "ecg:get_chart_data" %}' + '?start_time=' + startTime,
        type: 'GET',
        success: function (response) {
            if (response.data.length > 0) {
                let newValues = response.data.slice(count);  // 받은 데이터 중 미처리 부분만 추가
                newValues.forEach(function (value) {
                    chart.series[0].addPoint(value, true, false);
                });

                total += newValues.reduce((a, b) => a + b, 0);
                count += newValues.length;
                let average = total / count;

                if (newValues.length > 0) {
                    let newValue = newValues[newValues.length - 1];
                    if (newValue !== lastValue) {
                        document.getElementById('currentValue').innerText = '측정 심박수 - ' + newValue;
                        lastValue = newValue;
                    }
                    document.getElementById('average').innerText = '심박수 평균값 - ' + average.toFixed(2);
                }
            }
            fetchDataLoop(startTime); // 응답 수신 후 바로 다음 요청
        },
        error: function () {
            // 에러 발생 시 1초 후 재시도
            setTimeout(function () {
                fetchDataLoop(startTime);
            }, 1000);
        }
    });
    }
    </script>
    {% endblock %}
</body>
</html>

project/ecg/templates/ecg/chlist.html
<!-- disease_checklist_app/templates/disease_checklist_app/disease_checklist.html -->
{% extends 'page.html' %}
<html lang="ko-kr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    {% block title %}
    <h1 id="title">심장 질환 모니터링</h1>
    {% endblock title %}

    {% block content %}

<form method="post">
    {% csrf_token %}
    <h2> 건강 체크 </h2>
    <nav class="navbar bg-light">
        <div class="container-fluid">
            {{ user.last_name }}{{ user.first_name }}님
        </div>
    </nav>
    <table class="table table-hover" id="myTable" border="1" cellspacing="0" summary="진단기록">
        <colgroup>

            <col width = "30">
            <col width = "300">
            <col width = "170">
        </colgroup>
        <thead>
            <tr>
                <th>No.</th>
                <th>질문사항</th>
                <th>답변 (예, 아니오)</th>

            </tr>
        </thead>
        <tbody>
            {% for log in logs %}
            {% if not request.GET.q or log.login.user.username|lower in request.GET.q|lower %}
            <tr>
                <td>{{ log.login.user.last_name }} {{ log.login.user.first_name }}</td>
                <td>{{ log.login.user.username }}</td>
                <td>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="option1">
                        <label class="form-check-label" for="inlineRadio1">1</label>
                      </div>
                      <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2">
                        <label class="form-check-label" for="inlineRadio2">2</label>
                      </div>
                </td>
            </tr>
            <tr>
                <td>{{ log.login.user.last_name }} {{ log.login.user.first_name }}</td>
                <td>{{ log.login.user.username }}</td>
                <td>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="option1">
                        <label class="form-check-label" for="inlineRadio1">1</label>
                      </div>
                      <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2">
                        <label class="form-check-label" for="inlineRadio2">2</label>
                      </div>
                </td>
            </tr>

            {% endif %}
            {% empty %}
            <tr>
                <td colspan="6">No login/logout logs found.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}
</body>
</html>

project/ecg/templates/ecg/inform_detail.html
{% extends 'page.html' %}
<html lang="ko-kr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    {% block title %}
    <h1 id="title" class="text-center">심장 질환 모니터링</h1>
    {% endblock title %}

    {% block content %}
    <div class="container">
        <h2> 회원정보 </h2>
        <p><strong>이름 :</strong> {{ user.last_name }} {{ user.first_name }}</p>
        <p><strong>생년월일 :</strong> {{ user.birth }}</p>
        <p><strong>이메일 :</strong> {{ user.email }}</p>
        <p><strong>성별 :</strong>  {{ user.sex }}</p>
        <p><strong>혈액형 :</strong> {{ user.b_type }}</p>
        <p><strong>키 :</strong>  {{ user.height }}cm</p>
        <p><strong>몸무게 :</strong>  {{ user.weight }}kg</p>
    </div>
    {% endblock %}
</body>
</html>

project/ecg/templates/ecg/login.html
<html lang="ko-kr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only 부트스트랩 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <title>심장 질환 검사</title>
</head>
<body>
{% load static %}
<link rel="stylesheet" href="{% static 'login.css' %}">
    {% if error %}
    <p style="color: red;">{{ error }}</p>
    {% endif %}

    <style>
        .login-container {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
    
        .custom-input {
            width: 500px;
        }
    </style>

    <div class="login-container">
        <div class="login">
            <form method="POST">
                {% csrf_token %}
                <h1>심전도 모니터링</h1>
                <div class="form-floating mb-3">
                    <input class="form-control form-control-sm custom-input" type="text" name='username'  placeholder="아이디 입력">
                    <label for="username">아이디</label>
                </div>
    
                <div class="form-floating mb-3">
                    <input class="form-control form-control-sm custom-input" type="password" name='password' placeholder="비밀번호 입력">
                    <label for="password">비밀번호</label>
                </div>
    
                <div id="button">
                    <input class="btn btn-primary" type="submit" value="로그인">
                    <a href="{% url 'ecg:signup' %}" class="btn btn-primary" type="button">회원가입</a>
                </div>
            </form>
        </div>
    </div>
</body>
</html>

project/ecg/templates/ecg/ques.html
{% for question in questions %}
<div>
    <p>Total 'Yes': {{ question.total }}</p>
</div>
{% endfor %}

project/ecg/templates/ecg/questions.html
<!DOCTYPE html>
{% extends 'page.html' %}
<html lang="ko-kr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    {% block title %}
    <h1 id="title">심장 질환 모니터링</h1>
    {% endblock title %}

    {% block content %}
    
    <form id="questionsForm" method="post">
        {% csrf_token %}
        <h2> 건강 체크 </h2>

        <table class="table table-hover" id="myTable" border="1" cellspacing="0" summary="진단기록">
            <colgroup>
    
                <col width = "30">
                <col width = "300">
                <col width = "170">
            </colgroup>
            <thead>
                <tr>
                    <th>No.</th>
                    <th>질문사항</th>
                    <th>답변 (예, 아니오)</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>1</td>
                    <td>{{ form.question1.label_tag }}</td>
                    <td>{{ form.question1 }}</td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>{{ form.question2.label_tag }}</td>
                    <td>{{ form.question2 }}</td>
                </tr>
                <tr>
                    <td>3</td>
                    <td>{{ form.question3.label_tag }}</td>
                    <td>{{ form.question3 }}</td>
                </tr>
                <tr>
                    <td>4</td>
                    <td>{{ form.question4.label_tag }}</td>
                    <td>{{ form.question4 }}</td>
                </tr>
                <tr>
                    <td>5</td>
                    <td>{{ form.question5.label_tag }}</td>
                    <td>{{ form.question5 }}</td>
                </tr>
                <tr>
                    <td>6</td>
                    <td>{{ form.question6.label_tag }}</td>
                    <td>{{ form.question6 }}</td>
                </tr>
                <tr>
                    <td>7</td>
                    <td>{{ form.question7.label_tag }}</td>
                    <td>{{ form.question7 }}</td>
                </tr>
            </tbody>
        </table>
        <button class="btn btn-primary" type="submit">확인</button>
    </form>

    {% if result_message %}
        <script>
            alert("{{ result_message }}");
            window.location.href = "{% url 'ecg:record' %}";
        </script>
    {% endif %}

    {% endblock %}
</body>
</html>

project/ecg/templates/ecg/record.html
{% extends 'page.html' %}
<html lang="ko-kr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    {% block title %}
    <h1 id="title">심장 질환 모니터링</h1>
    {% endblock title %}

    {% block content %}
    <h2> 건강 기록 </h2>
    <nav class="navbar bg-light">
        <div class="container-fluid">
            {{ user.last_name }}{{ user.first_name }}님
        </div>
    </nav>
    <table class="table table-hover" id="myTable" border="1" cellspacing="0" summary="진단기록">
        <colgroup>
            <col width = "50">
            <col width = "50">
            <col width = "30">
            <col width = "50">
            <col width = "300">
        </colgroup>
        <thead>
            <tr>
                <th>No.</th>
                <th>진단 상태</th>
                <th>(평균)심박수</th>
                <th>건강상태</th>
                <th>기록시간</th>
            </tr>
        </thead>
        <tbody>
            {% for avg in all_avgs %}
            <tr>
                <td>{{ avg.id }}</td>
                <td>{{ avg.status }}</td>
                <td>{{ avg.avg|floatformat:"-1" }}</td>
                <td>{{ all_questions.first.status }}</td>
                <td>{{ avg.timestamp }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endblock %}
</body>
</html>

project/ecg/templates/ecg/signup.html
<!DOCTYPE html>
<html lang="ko-kr">
    <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <!-- CSS only 부트스트랩 -->
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
            <!-- JavaScript Bundle with Popper -->
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
            <title>심장 질환 검사</title>
        </head>
    <style>
        .error-text {
            color: red;
        }
    </style>
</head>
<body>
    <h2>회원가입</h2>
    
    <form method="post" action="{% url 'ecg:signup' %}">
        {% csrf_token %}
        
        {{ signupForm.as_p }}
        
        <button type="submit">회원가입</button>
    </form>
    <a href="{% url 'ecg:login'%}" class="nav-link">뒤로가기</a>
    <!-- Modal for Success -->
    <div id="successModal" style="display: none;">
        <p>Registration successful! You will be redirected to the login page.</p>
    </div>

    <!-- Modal for Error -->
    <div id="errorModal" style="display: none;">
        <p class="error-text" id="errorText"></p>
    </div>

    <script>
        // Script to display modals
        {% if request.method == "POST" %}
            {% if signupForm.errors %}
                // Display error modal with red text
                document.getElementById("errorText").innerHTML = "{{ signupForm.errors }}";
                document.getElementById("errorModal").style.display = "block";
            {% else %}
                // Display success modal
                document.getElementById("successModal").style.display = "block";
                // Redirect to the login page after a short delay
                setTimeout(function(){
                    window.location.href = "{% url 'ecg:login' %}";
                }, 3000);
            {% endif %}
        {% endif %}
    </script>
</body>
</html>